version: '3.1'

services:
    mysql:
        image: mysql
        environment:
          MYSQL_USER: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_pass"
        secrets:
          - source: "mysql_root_pass_v2"
            target: "mysql_root_pass"
        deploy:
            placement:
                constraints:
                    - node.role==manager

secrets:
  mysql_root_pass_v2:
    external: true

